-- ============================================================================
-- 025-fix-encoding-question-marks.sql
-- Fix corrupted question mark characters across all tables
-- Created: 2026-02-07
--
-- Problem: MySQL/WordPress lost accented characters during export, replacing
-- them with ASCII question marks (?). Each ? represents one lost character.
-- Double ?? represents one character whose 2 UTF-8 bytes were both lost.
--
-- Scope: ~592 rows across instrumenten, inkoop, gemeente, provincie
-- Approach: Explicit value-to-value replacement (manual + pattern-based)
-- Source: Manual research + linguistic pattern matching
--
-- IMPORTANT: Run this AFTER 024-fix-encoding-double-utf8.sql
-- ============================================================================

BEGIN;

-- === gemeente ===
UPDATE gemeente SET omschrijving = 'In onderwijsprog.Gelijk=Gelijkézetten jonge rolmodellen zich in voor diversiteit&tegen discriminatie
UPDATE gemeente SET omschrijving = 'Subsidie voor workshops en artistieke presentaties
UPDATE gemeente SET omschrijving = 'deel Miep Gies pleinéhunzestraat

-- === inkoop ===
UPDATE inkoop SET leverancier = '''t Stalhés training, stalling en dienstverlening' WHERE leverancier = '''t Stalh?s training, stalling en dienstverlening'; -- 1 row(s) [AUTO]
UPDATE inkoop SET leverancier = 'Öko-Institut E.V.' WHERE leverancier = '?ko-Institut E.V.'; -- 1 row(s) [AUTO]
UPDATE inkoop SET leverancier = 'Ärztekasse Rechtsmedizin' WHERE leverancier = '?rztekasse Rechtsmedizin'; -- 2 row(s) [AUTO]
UPDATE inkoop SET leverancier = 'Amrâth Born B.V.' WHERE leverancier = 'Amr?th Born B.V.'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'BABO Café B.V.' WHERE leverancier = 'BABO Caf?? B.V.'; -- 2 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'Bas Labruyére Mediakunstenaar' WHERE leverancier = 'Bas Labruy?re Mediakunstenaar'; -- 1 row(s) [AUTO]
UPDATE inkoop SET leverancier = 'Bastiaan Brüning Consultancy' WHERE leverancier = 'Bastiaan Br??ning Consultancy'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'C.E. Méller' WHERE leverancier = 'C.E. M?ller'; -- 1 row(s) [AUTO]
UPDATE inkoop SET leverancier = 'Café Corenmaet' WHERE leverancier = 'Caf?? Corenmaet'; -- 2 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'Café LEUK' WHERE leverancier = 'Caf?? LEUK'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'Café Le Montmartre de Paris' WHERE leverancier = 'Caf?? Le Montmartre de Paris'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'Café de Pepel' WHERE leverancier = 'Caf?? de Pepel'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'Coöperatie ''2D3D Design'' UA' WHERE leverancier = 'Co??peratie ''2D3D Design'' UA'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'Coöperatie Energie Samen UA' WHERE leverancier = 'Co??peratie Energie Samen UA'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'Co÷peratie RAV Fryslân U.A.' WHERE leverancier = 'Co÷peratie RAV Frysl?n U.A.'; -- 1 row(s) [AUTO]
UPDATE inkoop SET leverancier = 'Deutsche Gesellschaft für Rechtsmedizin e.V' WHERE leverancier = 'Deutsche Gesellschaft f?r Rechtsmedizin e.V'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'Eén Loket MK B.V.' WHERE leverancier = 'E?n Loket MK B.V.'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'Eetcafé Spinoza B.V.' WHERE leverancier = 'Eetcaf?? Spinoza B.V.'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'Eetcafé Vidocq B.V.' WHERE leverancier = 'Eetcaf?? Vidocq B.V.'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'FBN Juristen notarieël & fiscaal' WHERE leverancier = 'FBN Juristen notarie?l & fiscaal'; -- 1 row(s) [AUTO]
UPDATE inkoop SET leverancier = 'Fooddrôme B.V.' WHERE leverancier = 'Fooddr?me B.V.'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'Goya-Oriëntal B.V.' WHERE leverancier = 'Goya-Ori?ntal B.V.'; -- 2 row(s) [AUTO]
UPDATE inkoop SET leverancier = 'Ingenieurbéro Heitfeld - Schetelig' WHERE leverancier = 'Ingenieurb?ro Heitfeld - Schetelig'; -- 4 row(s) [AUTO]
UPDATE inkoop SET leverancier = 'Léon' WHERE leverancier = 'L?on'; -- 1 row(s) [AUTO]
UPDATE inkoop SET leverancier = 'Langenberg Gürses Vleugel Advocaten' WHERE leverancier = 'Langenberg G?rses Vleugel Advocaten'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'Michèle' WHERE leverancier = 'Mich?le'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'Nemzeti Szakértoi és Kutato Központ' WHERE leverancier = 'Nemzeti Szak?rtoi ?s Kutato K÷zpont'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'Oficiul Național al Viei si Vinului (O.N.V.V.)' WHERE leverancier = 'Oficiul Na?ional al Viei si Vinului (O.N.V.V.)'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'Országos Bírósági Hivatal ( National Office for the Judiciary)' WHERE leverancier = 'Orszßgos Bir?sßgi Hivatal ( National Office for the Judiciary)'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'Paeéens' WHERE leverancier = 'Pae?ens'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'Patiëntenfederatie Nederland' WHERE leverancier = 'Pati?ntenfederatie Nederland'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'Pedro Manuel Ribeiro de Carvalho Valério Vélia' WHERE leverancier = 'Pedro Manuel Ribeiro de Carvalho Val?rio V?lia'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'René van den Broek Party Catering B.V.' WHERE leverancier = 'Ren? van den Broek Party Catering B.V.'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'Stichting BètaBedrijvenBeurs' WHERE leverancier = 'Stichting B?taBedrijvenBeurs'; -- 1 row(s) [AUTO]
UPDATE inkoop SET leverancier = 'Tuincafé Botanica' WHERE leverancier = 'Tuincaf?? Botanica'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'Universitét Stuttgart' WHERE leverancier = 'Universit?t Stuttgart'; -- 2 row(s) [AUTO]
UPDATE inkoop SET leverancier = 'Van Dunné Advies en Management' WHERE leverancier = 'Van Dunn?? Advies en Management'; -- 1 row(s) [MANUAL]
UPDATE inkoop SET leverancier = 'imq - Ingenieurbetrieb für Materialprüfung, Qualitätssicherung und Schweißtechnik GmbH' WHERE leverancier = 'imq - Ingenieurbetrieb f³r Materialpr³fung, Qualitõtssicherung und Schwei?technik GmbH'; -- 1 row(s) [MANUAL]

-- === instrumenten ===
UPDATE instrumenten SET ontvanger = '''t Klöske' WHERE ontvanger = '''t Kl??ske'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Öz Sefa Meubel B.V.' WHERE ontvanger = '?z Sefa Meubel B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Özdemir Beheer B.V.' WHERE ontvanger = '?zdemir Beheer B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Özveren Vastgoed B.V.' WHERE ontvanger = '?zveren Vastgoed B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Açaí Events B.V.' WHERE ontvanger = 'A?a? Events B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'ABÉAZ Student B.V.' WHERE ontvanger = 'AB?AZ Student B.V.'; -- 2 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'ABÉAZ Vervoersregie B.V.' WHERE ontvanger = 'AB?AZ Vervoersregie B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'ABC ''t Tùpke' WHERE ontvanger = 'ABC ''t T?pke'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'ADZ Industriële Verhuizingen B.V.' WHERE ontvanger = 'ADZ Industri?le Verhuizingen B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'AUDIËNTIA Services' WHERE ontvanger = 'AUDI?NTIA Services'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Aardse Orchideeën B.V.' WHERE ontvanger = 'Aardse Orchidee?n B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Academie Sociale Hygiëne B.V.' WHERE ontvanger = 'Academie Sociale Hygi?ne B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Allro-Plast Carrosserieën B.V.' WHERE ontvanger = 'Allro-Plast Carrosserie?n B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Altaïr Begeleiding' WHERE ontvanger = 'Alta?r Begeleiding'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'André van Olst B.V.' WHERE ontvanger = 'Andr? van Olst B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'ArtiMedés B.V.' WHERE ontvanger = 'ArtiMed?s B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Asfalea Assurantiën Financiering Vliegreizen B.V.' WHERE ontvanger = 'Asfalea Assuranti?n Financiering Vliegreizen B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Atelier de l''Armée B.V.' WHERE ontvanger = 'Atelier de l''Arm?e B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Auth. S. Ramen Noodle Takumi Désseldorf(RB)BV' WHERE ontvanger = 'Auth. S. Ramen Noodle Takumi D?sseldorf(RB)BV'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Auto Wüst Dordrecht B.V.' WHERE ontvanger = 'Auto W?st Dordrecht B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Auto Wüst Hellevoetsluis B.V.' WHERE ontvanger = 'Auto W?st Hellevoetsluis B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Bömar B.V.' WHERE ontvanger = 'B?mar B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Bér Huijnen Landbouwmechanisatie B.V.' WHERE ontvanger = 'B?r Huijnen Landbouwmechanisatie B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Bér Software B.V.' WHERE ontvanger = 'B?r Software B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Bésta B.V.' WHERE ontvanger = 'B?sta B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Bar Péche' WHERE ontvanger = 'Bar P?che'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Barça Amsterdam B.V.' WHERE ontvanger = 'Bar?a Amsterdam B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Baskèts B.V.' WHERE ontvanger = 'Bask?ts B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Bauservice Méhle-Haufe B.V.' WHERE ontvanger = 'Bauservice M?hle-Haufe B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Bjérn B.V.' WHERE ontvanger = 'Bj?rn B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Blond toégo B.V.' WHERE ontvanger = 'Blond to?go B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Boutique Hotel/Résidence Karel de Stoute' WHERE ontvanger = 'Boutique Hotel/R?sidence Karel de Stoute'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Brasserie Délicat B.V.' WHERE ontvanger = 'Brasserie D?licat B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Bridge Sociëteit Almelo' WHERE ontvanger = 'Bridge Soci?teit Almelo'; -- 2 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Brouwersnès B.V.' WHERE ontvanger = 'Brouwersn?s B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Buchhandlung Walther Kénig' WHERE ontvanger = 'Buchhandlung Walther K?nig'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'C. ?iftéi Beheer B.V.' WHERE ontvanger = 'C. ?ift?i Beheer B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Céleste Originals B.V.' WHERE ontvanger = 'C?leste Originals B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Cönect Telecom B.V.' WHERE ontvanger = 'C?nect Telecom B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Césant Korenbeurs' WHERE ontvanger = 'C?sant Korenbeurs'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Césant Wijnhaven Catering B.V.' WHERE ontvanger = 'C?sant Wijnhaven Catering B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Céte Bar Bistro' WHERE ontvanger = 'C?te Bar Bistro'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Café Aimée B.V.' WHERE ontvanger = 'Caf? Aim?e B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'CaféEKalkhoven B.V.' WHERE ontvanger = 'Caf?EKalkhoven B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Caréon Consultancy B.V.' WHERE ontvanger = 'Car?on Consultancy B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Carel Wüst Museum B.V.' WHERE ontvanger = 'Carel W?st Museum B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Centre de Cours Alliance Franéaise de La Haye' WHERE ontvanger = 'Centre de Cours Alliance Fran?aise de La Haye'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Centrum voor Leven en Intuétie B.V.' WHERE ontvanger = 'Centrum voor Leven en Intu?tie B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Centurion Financiële Dienstverlening' WHERE ontvanger = 'Centurion Financi?le Dienstverlening'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Chéteau des Connaisseurs B.V.' WHERE ontvanger = 'Ch?teau des Connaisseurs B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Christel. Gereform. Kerk Veenendaal (Pniél)' WHERE ontvanger = 'Christel. Gereform. Kerk Veenendaal (Pni?l)'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Cinéart Nederland B.V.' WHERE ontvanger = 'Cin?art Nederland B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Club De Pétanque Heerlen' WHERE ontvanger = 'Club De P?tanque Heerlen'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Club de Pétanque ''Les Cailloux''' WHERE ontvanger = 'Club de P?tanque ''Les Cailloux'''; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Coöp. tot Exploit. Landb.werkt. Sch. Duiv. WA' WHERE ontvanger = 'Co?p. tot Exploit. Landb.werkt. Sch. Duiv. WA'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Coöperatie ''t Duuvelke U.A.' WHERE ontvanger = 'Co?peratie ''t Duuvelke U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Coöperatie AVEBE U.A.' WHERE ontvanger = 'Co?peratie AVEBE U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Coöperatie AVEBE UA' WHERE ontvanger = 'Co?peratie AVEBE UA'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Coöperatie De Duitse Bakker (ML) U.A.' WHERE ontvanger = 'Co?peratie De Duitse Bakker (ML) U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Coöperatie Devlab, Development Laboratories' WHERE ontvanger = 'Co?peratie Devlab, Development Laboratories'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Coöperatie Flevolands Agrarisch Collectief U.A.' WHERE ontvanger = 'Co?peratie Flevolands Agrarisch Collectief U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Coöperatie Kennis Transfer Centrum Proefboerderij Zegveld U.A.' WHERE ontvanger = 'Co?peratie Kennis Transfer Centrum Proefboerderij Zegveld U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Coöperatie Ontwikkeling Leerpark U.A.' WHERE ontvanger = 'Co?peratie Ontwikkeling Leerpark U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Coöperatie Ruimte U.A.' WHERE ontvanger = 'Co?peratie Ruimte U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Coöperatie Technologie & Zorg Academie Groningen (TZA Groningen) U.A.' WHERE ontvanger = 'Co?peratie Technologie & Zorg Academie Groningen (TZA Groningen) U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Coöperatie Weekmarkten Vlaardingen U.A.' WHERE ontvanger = 'Co?peratie Weekmarkten Vlaardingen U.A.'; -- 2 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Coöperatief Energie Dienstenbedrijf Rivierenland B.A.' WHERE ontvanger = 'Co?peratief Energie Dienstenbedrijf Rivierenland B.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Coöperatief Horeca Centrum Rietplas U.A.' WHERE ontvanger = 'Co?peratief Horeca Centrum Rietplas U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Coöperatieve INZET I U.A.' WHERE ontvanger = 'Co?peratieve INZET I U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Coöperatieve Tuinbouwveiling Zaltbommel en Omstreken B.A.' WHERE ontvanger = 'Co?peratieve Tuinbouwveiling Zaltbommel en Omstreken B.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Coöperatieve Vereniging: ''Aardappelbewaarplaats Altena'' U.A.' WHERE ontvanger = 'Co?peratieve Vereniging: ''Aardappelbewaarplaats Altena'' U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Coöperatieve vereniging In Alles Ghetrou U.A.' WHERE ontvanger = 'Co?peratieve vereniging In Alles Ghetrou U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Coöperatieve vereniging NLD energie U.A.' WHERE ontvanger = 'Co?peratieve vereniging NLD energie U.A.'; -- 3 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Coördinatie-Centrum NED B.V.' WHERE ontvanger = 'Co?rdinatie-Centrum NED B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Commerciële Radio Brabant B.V.' WHERE ontvanger = 'Commerci?le Radio Brabant B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Commerciële Radio Zuid Nederland B.V.' WHERE ontvanger = 'Commerci?le Radio Zuid Nederland B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Complet Système B.V.' WHERE ontvanger = 'Complet Syst?me B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Concilio adviseren - tekenen - coördineren B.V.' WHERE ontvanger = 'Concilio adviseren - tekenen - co?rdineren B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Culinaire Gilde Brabanéonne' WHERE ontvanger = 'Culinaire Gilde Braban?onne'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'CymPha Orchideeën B.V.' WHERE ontvanger = 'CymPha Orchidee?n B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'D.C.U. B.V. t.h.o.d.n. The Döner Company Beverwijk CS' WHERE ontvanger = 'D.C.U. B.V. t.h.o.d.n. The D?ner Company Beverwijk CS'; -- 2 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Dé tandprotheticus B.V.' WHERE ontvanger = 'D? tandprotheticus B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'DéBron Control B.V.' WHERE ontvanger = 'D?Bron Control B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'DéDé B.V.' WHERE ontvanger = 'D?D? B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'DéOéCéSTAP' WHERE ontvanger = 'D?O?C?STAP'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Délifrance Haarlem B.V.' WHERE ontvanger = 'D?lifrance Haarlem B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Délifrance-Hellevoetsluis B.V.' WHERE ontvanger = 'D?lifrance-Hellevoetsluis B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Döner Baba B.V.' WHERE ontvanger = 'D?ner Baba B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Döner House B.V.' WHERE ontvanger = 'D?ner House B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Dönerix' WHERE ontvanger = 'D?nerix'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Déro Cosmetics B.V.' WHERE ontvanger = 'D?ro Cosmetics B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Dévak Truckschadeservice B.V.' WHERE ontvanger = 'D?vak Truckschadeservice B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Déyen B.V.' WHERE ontvanger = 'D?yen B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Da Gabriële B.V.' WHERE ontvanger = 'Da Gabri?le B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Daniél''s Gym Boxtel B.V.' WHERE ontvanger = 'Dani?l''s Gym Boxtel B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Daniéls Advocaten B.V.' WHERE ontvanger = 'Dani?ls Advocaten B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'De Aprés Skihut' WHERE ontvanger = 'De Apr?s Skihut'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'De Aprés Skihut Bierkeller' WHERE ontvanger = 'De Apr?s Skihut Bierkeller'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'De Bourgondiër B.V.' WHERE ontvanger = 'De Bourgondi?r B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'De Groote Sociëteit' WHERE ontvanger = 'De Groote Soci?teit'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'De Lèghe Polder' WHERE ontvanger = 'De L?ghe Polder'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'De Mörthal' WHERE ontvanger = 'De M?rthal'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'De Orchideeënhoeve B.V.' WHERE ontvanger = 'De Orchidee?nhoeve B.V.'; -- 2 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'De Plekkenmakers Coöperatie U.A.' WHERE ontvanger = 'De Plekkenmakers Co?peratie U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'De Rooy Makelaardij & Assurantiën B.V.' WHERE ontvanger = 'De Rooy Makelaardij & Assuranti?n B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'De Ruïne' WHERE ontvanger = 'De Ru?ne'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'De Séndobbe' WHERE ontvanger = 'De S?ndobbe'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Delftsche Studenten Sociëteit ''Phoenix''' WHERE ontvanger = 'Delftsche Studenten Soci?teit ''Phoenix'''; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Deventer Buitensociëteit' WHERE ontvanger = 'Deventer Buitensoci?teit'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Dorpencoöperatie Reitdiepdal U.A.' WHERE ontvanger = 'Dorpenco?peratie Reitdiepdal U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Dorpscoöperatie Heide U.A.' WHERE ontvanger = 'Dorpsco?peratie Heide U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Dorpshuis Drempt Gildehéfke' WHERE ontvanger = 'Dorpshuis Drempt Gildeh?fke'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Dorpshuis Tènawerth' WHERE ontvanger = 'Dorpshuis T?nawerth'; -- 2 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Drogenbroek''s Fruit B.V.' WHERE ontvanger = 'Drogenbroek?s Fruit B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'EIT Ménchen GmbH & Co. KG' WHERE ontvanger = 'EIT M?nchen GmbH & Co. KG'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'ELM Industriële Automatisering B.V.' WHERE ontvanger = 'ELM Industri?le Automatisering B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Eenkhoorn Financiële Dienstverlening B.V.' WHERE ontvanger = 'Eenkhoorn Financi?le Dienstverlening B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'El Niéo B.V.' WHERE ontvanger = 'El Ni?o B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Eliéns Exclusieve Interieurs B.V.' WHERE ontvanger = 'Eli?ns Exclusieve Interieurs B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Eliléne B.V.' WHERE ontvanger = 'Elil?ne B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Entreprenér' WHERE ontvanger = 'Entrepren?r'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Essaïdi Applied Sciences B.V.' WHERE ontvanger = 'Essa?di Applied Sciences B.V.'; -- 2 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Estée Culinair Events B.V.' WHERE ontvanger = 'Est?e Culinair Events B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Féilte B.V.' WHERE ontvanger = 'F?ilte B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Féte du Champagne & Vin' WHERE ontvanger = 'F?te du Champagne & Vin'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'FDR & Associés B.V.' WHERE ontvanger = 'FDR & Associ?s B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Fidélité Bruidsmode B.V.' WHERE ontvanger = 'Fid?lit? Bruidsmode B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Flégel Production N.V.' WHERE ontvanger = 'Fl?gel Production N.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Folkshegeskoalle Schylgeralân' WHERE ontvanger = 'Folkshegeskoalle Schylgeral?n'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Fooddrôme B.V.' WHERE ontvanger = 'Fooddr?me B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Frébel B.V.' WHERE ontvanger = 'Fr?bel B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'FraéMelco B.V.' WHERE ontvanger = 'Fra?Melco B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Fraunhofer-Gesellschaft zur Férderung der angewandten Forschung' WHERE ontvanger = 'Fraunhofer-Gesellschaft zur F?rderung der angewandten Forschung'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Frisk-Fruktergård B.V.' WHERE ontvanger = 'Frisk-Frukterg?rd B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Fryslân Fan Plaza Heerenveen' WHERE ontvanger = 'Frysl?n Fan Plaza Heerenveen'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Furnée & Co B.V.' WHERE ontvanger = 'Furn?e & Co B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Future Food Fund Coöperatief U.A.' WHERE ontvanger = 'Future Food Fund Co?peratief U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'GéEBosmans Verspaningtechniek B.V.' WHERE ontvanger = 'G?EBosmans Verspaningtechniek B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Göbel Haarmode B.V.' WHERE ontvanger = 'G?bel Haarmode B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Géler Logistics B.V.' WHERE ontvanger = 'G?ler Logistics B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Géncé B.V.' WHERE ontvanger = 'G?nc? B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Génes B.V.' WHERE ontvanger = 'G?nes B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Gértz Rozendaal B.V.' WHERE ontvanger = 'G?rtz Rozendaal B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Götts B.V.' WHERE ontvanger = 'G?tts B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Gézel B.V.' WHERE ontvanger = 'G?zel B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Gasterij Oatmösssche B.V.' WHERE ontvanger = 'Gasterij Oatm?ssche B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Gastfrij Fryslân B.V.' WHERE ontvanger = 'Gastfrij Frysl?n B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Gestión de propiedad B.V.' WHERE ontvanger = 'Gesti?n de propiedad B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Goya-Oriëntal B.V.' WHERE ontvanger = 'Goya-Ori?ntal B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Grand Hôtel Amrâth Amsterdam B.V.' WHERE ontvanger = 'Grand H?tel Amr?th Amsterdam B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Grandcafé Restaurant ''t Smelnehûs B.V.' WHERE ontvanger = 'Grandcaf? Restaurant ''t Smelneh?s B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Groote Sociëteit Haagsche Club-Plaats Royaal' WHERE ontvanger = 'Groote Soci?teit Haagsche Club-Plaats Royaal'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'H&O Financiële Administraties B.V.' WHERE ontvanger = 'H&O Financi?le Administraties B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'H. Biëer B.V.' WHERE ontvanger = 'H. Bi?er B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Höman Verhuurservice B.V.' WHERE ontvanger = 'H?man Verhuurservice B.V.'; -- 2 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Héroult Marine Modules B.V.' WHERE ontvanger = 'H?roult Marine Modules B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Hétes Culture B.V.' WHERE ontvanger = 'H?tes Culture B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Hanenberg Industriële Bouw B.V.' WHERE ontvanger = 'Hanenberg Industri?le Bouw B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Het Commerciële Huis B.V.' WHERE ontvanger = 'Het Commerci?le Huis B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Hoffelijk Financiële Zorg B.V.' WHERE ontvanger = 'Hoffelijk Financi?le Zorg B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Holding I. Németh B.V.' WHERE ontvanger = 'Holding I. N?meth B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Honnebier Industriële Appendages B.V.' WHERE ontvanger = 'Honnebier Industri?le Appendages B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Hortilux Schröder B.V.' WHERE ontvanger = 'Hortilux Schr?der B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Hotel BommeljeéEB.V.' WHERE ontvanger = 'Hotel Bommelj?EB.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Hotel Mariénhage B.V.' WHERE ontvanger = 'Hotel Mari?nhage B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Huiskamer de Groote Sociëteit' WHERE ontvanger = 'Huiskamer de Groote Soci?teit'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Hygiëne Control Benelux B.V.' WHERE ontvanger = 'Hygi?ne Control Benelux B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'INTERREG Twee Zeeën' WHERE ontvanger = 'INTERREG Twee Zee?n'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'IRE EHF NL Prinsengracht PropCo Coöperatief U.A.' WHERE ontvanger = 'IRE EHF NL Prinsengracht PropCo Co?peratief U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Industriële Diensten Heino B.V.' WHERE ontvanger = 'Industri?le Diensten Heino B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Industriële Elektrotechniek Terneuzen B.V.' WHERE ontvanger = 'Industri?le Elektrotechniek Terneuzen B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Industriële Handelsonderneming Nieuwenhagen B.V.' WHERE ontvanger = 'Industri?le Handelsonderneming Nieuwenhagen B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Industriële- en Handelsonderneming A. van der Wagt B.V.' WHERE ontvanger = 'Industri?le- en Handelsonderneming A. van der Wagt B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'It Foarúnder' WHERE ontvanger = 'It Foar?nder'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'It Werflân' WHERE ontvanger = 'It Werfl?n'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'J.M.G. Meertens Chévremont B.V.' WHERE ontvanger = 'J.M.G. Meertens Ch?vremont B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Jénger Accountancy' WHERE ontvanger = 'J?nger Accountancy'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Joél Boreel Holding B.V.' WHERE ontvanger = 'Jo?l Boreel Holding B.V.'; -- 2 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Joél-Max B.V.' WHERE ontvanger = 'Jo?l-Max B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Jongerensociëteit ''De Aap''' WHERE ontvanger = 'Jongerensoci?teit ''De Aap'''; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Jonker Carrosserieën B.V.' WHERE ontvanger = 'Jonker Carrosserie?n B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'José Velésquez Amazing Beauty' WHERE ontvanger = 'Jos? Vel?squez Amazing Beauty'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Jour de féte B.V.' WHERE ontvanger = 'Jour de f?te B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Kébol B.V.' WHERE ontvanger = 'K?bol B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Kébol Plants B.V.' WHERE ontvanger = 'K?bol Plants B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Kénig Nederland B.V.' WHERE ontvanger = 'K?nig Nederland B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Körvers Piping B.V.' WHERE ontvanger = 'K?rvers Piping B.V.'; -- 2 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Käse Bekabeling B.V.' WHERE ontvanger = 'K?se Bekabeling B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Köster Alkmaar B.V.' WHERE ontvanger = 'K?ster Alkmaar B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Karhof Carrosserieën Purmerend B.V.' WHERE ontvanger = 'Karhof Carrosserie?n Purmerend B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Karma Sociëte Lounge B.V.' WHERE ontvanger = 'Karma Soci?te Lounge B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Katholieke Studenten Sociëteit Alcuin' WHERE ontvanger = 'Katholieke Studenten Soci?teit Alcuin'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Kauf Dich Glécklich B.V.' WHERE ontvanger = 'Kauf Dich Gl?cklich B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Klöh Service Management Nederland B.V.' WHERE ontvanger = 'Kl?h Service Management Nederland B.V.'; -- 2 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Koéter Vastgoed Adviseurs B.V.' WHERE ontvanger = 'Ko?ter Vastgoed Adviseurs B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Kon. Ver. Agent Halverhout-Zwart-Zurméhlen BV' WHERE ontvanger = 'Kon. Ver. Agent Halverhout-Zwart-Zurm?hlen BV'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Koninklijke Coöperatie Cosun UA' WHERE ontvanger = 'Koninklijke Co?peratie Cosun UA'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Kumpulan Reénie- en Congrescentrum' WHERE ontvanger = 'Kumpulan Re?nie- en Congrescentrum'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Lückman Beheer B.V.' WHERE ontvanger = 'L?ckman Beheer B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Löhr Zandvoort B.V.' WHERE ontvanger = 'L?hr Zandvoort B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Léon Promotions B.V.' WHERE ontvanger = 'L?on Promotions B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'LéonLéon B.V.' WHERE ontvanger = 'L?onL?on B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'La Bergére Hospitality Group B.V.' WHERE ontvanger = 'La Berg?re Hospitality Group B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'La Féte B.V.' WHERE ontvanger = 'La F?te B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'La deuxiéme fois B.V.' WHERE ontvanger = 'La deuxi?me fois B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Lagardére Travel Retail Stations B.V.' WHERE ontvanger = 'Lagard?re Travel Retail Stations B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Le Coeur - Bistrothéque B.V.' WHERE ontvanger = 'Le Coeur - Bistroth?que B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Le Méridien ''s-Hertogenbosch B.V.' WHERE ontvanger = 'Le Meridi?n ''s-Hertogenbosch B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Le Réve Maastricht B.V.' WHERE ontvanger = 'Le R?ve Maastricht B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Lederwaren Daniélle B.V.' WHERE ontvanger = 'Lederwaren Dani?lle B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Lekker Gewoon B.V.' WHERE ontvanger = 'Lekker Gewo?n B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Let''s Serve B.V.' WHERE ontvanger = 'Let?s Serve B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Liévre B.V.' WHERE ontvanger = 'Li?vre B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Linchérie Arendshof' WHERE ontvanger = 'Linch?rie Arendshof'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Luma Coöperatie U.A.' WHERE ontvanger = 'Luma Co?peratie U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Luyckx Industriële Reiniging en Constructies B.V.' WHERE ontvanger = 'Luyckx Industri?le Reiniging en Constructies B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Möck B.V.' WHERE ontvanger = 'M?ck B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Méller Autoschade Centrum B.V.' WHERE ontvanger = 'M?ller Autoschade Centrum B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Méller Centrale Diensten B.V.' WHERE ontvanger = 'M?ller Centrale Diensten B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Méller Van Tol B.V.' WHERE ontvanger = 'M?ller Van Tol B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Möve' WHERE ontvanger = 'M?ve'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'MarcelisDékavé B.V.' WHERE ontvanger = 'MarcelisD?kav? B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Mariéndonk B.V.' WHERE ontvanger = 'Mari?ndonk B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Mariénhof Amersfoort B.V.' WHERE ontvanger = 'Mari?nhof Amersfoort B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Masèvon Technology' WHERE ontvanger = 'Mas?von Technology'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Masséus Mode B.V.' WHERE ontvanger = 'Mass?us Mode B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Math Brassée B.V.' WHERE ontvanger = 'Math Brass?e B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Mathé de Groot Reisbureau B.V.' WHERE ontvanger = 'Math? de Groot Reisbureau B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Metabolic Coöperatief U.A.' WHERE ontvanger = 'Metabolic Co?peratief U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Minéral B.V.' WHERE ontvanger = 'Min?ral B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Ministerie van Financiën' WHERE ontvanger = 'Ministerie van Financi?n'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Modehuis Elysée B.V.' WHERE ontvanger = 'Modehuis Elys?e B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Museum Belvédére' WHERE ontvanger = 'Museum Belv?d?re'; -- 2 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Music Lease Coöperatie U.A.' WHERE ontvanger = 'Music Lease Co?peratie U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Nieuwe of Litteraire Sociëteit De Witte' WHERE ontvanger = 'Nieuwe of Litteraire Soci?teit De Witte'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Ological Toilethygiëne B.V.' WHERE ontvanger = 'Ological Toilethygi?ne B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Omgevingshuis Coöperatie U.A.' WHERE ontvanger = 'Omgevingshuis Co?peratie U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Ontvanger Subsidieregeling Jonge Agrariërs' WHERE ontvanger = 'Ontvanger Subsidieregeling Jonge Agrari?rs'; -- 3 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Onyx Développement SAS' WHERE ontvanger = 'Onyx D?veloppement SAS'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Oriënt. Jap. Rest. ''Gouden Huis Almere'' B.V.' WHERE ontvanger = 'Ori?nt. Jap. Rest. ''Gouden Huis Almere'' B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Oriëntal Andijk B.V.' WHERE ontvanger = 'Ori?ntal Andijk B.V.'; -- 2 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Oriëntal Beef Products B.V.' WHERE ontvanger = 'Ori?ntal Beef Products B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Oriëntal Green House' WHERE ontvanger = 'Ori?ntal Green House'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Oriëntal Restaurant Noordwijkerhout B.V.' WHERE ontvanger = 'Ori?ntal Restaurant Noordwijkerhout B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Oriëntal Tower B.V.' WHERE ontvanger = 'Ori?ntal Tower B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'P.A.H.M. Klésters Holding B.V.' WHERE ontvanger = 'P.A.H.M. Kl?sters Holding B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Pübhéla B.V.' WHERE ontvanger = 'P?bh?la B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Pétanquevereniging Le Chéteau' WHERE ontvanger = 'P?tanquevereniging Le Ch?teau'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Püttmann Juweliers' WHERE ontvanger = 'P?ttmann Juweliers'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'PIBLW-Reéntegratie & Inburgering' WHERE ontvanger = 'PIBLW-Re?ntegratie & Inburgering'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Pannékoek B.V.' WHERE ontvanger = 'Pann?koek B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Pannekoek Orchideeën B.V.' WHERE ontvanger = 'Pannekoek Orchidee?n B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Party Catering Trés Bien B.V.' WHERE ontvanger = 'Party Catering Tr?s Bien B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Partycentrum ''t Héfke B.V.' WHERE ontvanger = 'Partycentrum ''t H?fke B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Peek Von Schökkmann' WHERE ontvanger = 'Peek Von Sch?kkmann'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Peek Von Schökkmann B.V.' WHERE ontvanger = 'Peek Von Sch?kkmann B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Petit Géteau B.V.' WHERE ontvanger = 'Petit G?teau B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Pierét Haarlem B.V.' WHERE ontvanger = 'Pier?t Haarlem B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Playdôme Roosendaal B.V.' WHERE ontvanger = 'Playd?me Roosendaal B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Plusön B.V.' WHERE ontvanger = 'Plus??n B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Potéto Potéto Roermond B.V.' WHERE ontvanger = 'Pot?to Pot?to Roermond B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Prévu Expo B.V.' WHERE ontvanger = 'Pr?vu Expo B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Prévu Projectmanagement en Reclame B.V.' WHERE ontvanger = 'Pr?vu Projectmanagement en Reclame B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Profacare Hygiëneservice B.V.' WHERE ontvanger = 'Profacare Hygi?neservice B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Prominés B.V.' WHERE ontvanger = 'Promin?s B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Réling Import B.V.' WHERE ontvanger = 'R?ling Import B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Rötjes Young Plants B.V.' WHERE ontvanger = 'R?tjes Young Plants B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Röttjers Schoenmode B.V.' WHERE ontvanger = 'R?ttjers Schoenmode B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'RISØR B.V.' WHERE ontvanger = 'RIS?R B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Raphaéls B.V.' WHERE ontvanger = 'Rapha?ls B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Reünistenvereniging Villa Veluvia' WHERE ontvanger = 'Re?nistenvereniging Villa Veluvia'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Reisbureau TéDéTé B.V.' WHERE ontvanger = 'Reisbureau T?D?T? B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'RenéEvan Dijk Freesia B.V.' WHERE ontvanger = 'Ren?Evan Dijk Freesia B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Renél Beheer B.V.' WHERE ontvanger = 'Ren?l Beheer B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Restaurant Céline B.V.' WHERE ontvanger = 'Restaurant C?line B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Restaurant FF Swanjée B.V.' WHERE ontvanger = 'Restaurant FF Swanj?? B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Restaurant Rijnmozaék' WHERE ontvanger = 'Restaurant Rijnmoza?k'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Restaurant Yucatén Leeuwarden B.V.' WHERE ontvanger = 'Restaurant Yucat?n Leeuwarden B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Rob Peetoom Hairsé Amsterdam' WHERE ontvanger = 'Rob Peetoom Hair?? Amsterdam'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'SaléPro B.V.' WHERE ontvanger = 'Sal?Pro B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Salle-Privée B.V.' WHERE ontvanger = 'Salle-Priv?e B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Samenwerkende Kredietunies en Kredietcoöp.' WHERE ontvanger = 'Samenwerkende Kredietunies en Kredietco?p.'; -- 4 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Samsøe & Samsøe Amsterdam B.V.' WHERE ontvanger = 'Sams?e & Sams?e Amsterdam B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Schélke & Mayr Benelux B.V.' WHERE ontvanger = 'Sch?lke & Mayr Benelux B.V.'; -- 2 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Schréder Modestoffen en Fournituren B.V.' WHERE ontvanger = 'Schr?der Modestoffen en Fournituren B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Silderhuis-Löwik B.V.' WHERE ontvanger = 'Silderhuis-L?wik B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'SkyTeam Airline Alliance Management Coöperatie U.A.' WHERE ontvanger = 'SkyTeam Airline Alliance Management Co?peratie U.A.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Sláinte B.V.' WHERE ontvanger = 'Sl?inte B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Sméagol B.V.' WHERE ontvanger = 'Sm?agol B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Sociëteit ''De Unie''' WHERE ontvanger = 'Soci?teit ''De Unie'''; -- 2 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Sociëteit ''Eendragt Maakt Magt''' WHERE ontvanger = 'Soci?teit ''Eendragt Maakt Magt'''; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Sociëteit ''tot Nut Ende Vermaeck''' WHERE ontvanger = 'Soci?teit ''tot Nut Ende Vermaeck'''; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Sociëteit Akademeia' WHERE ontvanger = 'Soci?teit Akademeia'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Sociëteit Asterion' WHERE ontvanger = 'Soci?teit Asterion'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Sociëteit Tyche' WHERE ontvanger = 'Soci?teit Tyche'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Sociëteit Vereeniging' WHERE ontvanger = 'Soci?teit Vereeniging'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Sociëteit aan de Maas B.V.' WHERE ontvanger = 'Soci?teit aan de Maas B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Sociëteit der GSV' WHERE ontvanger = 'Soci?teit der GSV'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Sociëteitsvereniging Boccaccio' WHERE ontvanger = 'Soci?teitsvereniging Boccaccio'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Spéir B.V.' WHERE ontvanger = 'Sp?ir B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Spa Supréme B.V.' WHERE ontvanger = 'Spa Supr?me B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Spaghetteria Daniél Stalpertstraat B.V.' WHERE ontvanger = 'Spaghetteria Dani?l Stalpertstraat B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Sportsociëteit Reuvers Maastricht B.V.' WHERE ontvanger = 'Sportsoci?teit Reuvers Maastricht B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stg tot ISH vd Dierg. vh Kon. Zoöl. Genootsc. Natura Artis Magistra' WHERE ontvanger = 'Stg tot ISH vd Dierg. vh Kon. Zo?l. Genootsc. Natura Artis Magistra'; -- 3 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Sticht. Wijkontmoet.centr. (WOC)''t Schépke' WHERE ontvanger = 'Sticht. Wijkontmoet.centr. (WOC)''t Sch?pke'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Boulodréme Maastricht' WHERE ontvanger = 'Stichting Boulodr?me Maastricht'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Continuéteit Omniversum' WHERE ontvanger = 'Stichting Continu?teit Omniversum'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Dagbesteding DéDéD Deventer' WHERE ontvanger = 'Stichting Dagbesteding D?D?D Deventer'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting De Chétel sur place' WHERE ontvanger = 'Stichting De Ch?tel sur place'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting De Meuleböök' WHERE ontvanger = 'Stichting De Meuleb??k'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Stichting Doarpshés ''De Moeting''' WHERE ontvanger = 'Stichting Doarpsh?s ''De Moeting'''; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Exploitatie Sociëteit (SES)' WHERE ontvanger = 'Stichting Exploitatie Soci?teit (SES)'; -- 2 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Exploitatie Sociëteit La Confrerie' WHERE ontvanger = 'Stichting Exploitatie Soci?teit La Confrerie'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Exploitatie Sociëteit Quintus' WHERE ontvanger = 'Stichting Exploitatie Soci?teit Quintus'; -- 2 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Filmtheater de Nieuwe Scène' WHERE ontvanger = 'Stichting Filmtheater de Nieuwe Sc?ne'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Stichting Flamenco Biénnale' WHERE ontvanger = 'Stichting Flamenco Bi?nnale'; -- 2 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Foenix Kringloop en reéntegratie' WHERE ontvanger = 'Stichting Foenix Kringloop en re?ntegratie'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Gemeenschapshuis De Héllekes' WHERE ontvanger = 'Stichting Gemeenschapshuis De H?llekes'; -- 2 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Gemeenschapshuis in Kepél' WHERE ontvanger = 'Stichting Gemeenschapshuis in Kep?l'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting It Blauhûster Skûtsje' WHERE ontvanger = 'Stichting It Blauh?ster Sk?tsje'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Stichting KERSTVEILING MARIéNHEEM' WHERE ontvanger = 'Stichting KERSTVEILING MARI?NHEEM'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Lumiére Cinema' WHERE ontvanger = 'Stichting Lumi?re Cinema'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Mézaan' WHERE ontvanger = 'Stichting M?zaan'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Stichting Mariapoli Mariénkroon' WHERE ontvanger = 'Stichting Mariapoli Mari?nkroon'; -- 2 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Mienskipssintrum It GeaHés' WHERE ontvanger = 'Stichting Mienskipssintrum It GeaH?s'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Multicultureel Podium Mozaéek' WHERE ontvanger = 'Stichting Multicultureel Podium Moza?ek'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Multifunctioneel Centrum De Auw Sjoeël Ubachsberg' WHERE ontvanger = 'Stichting Multifunctioneel Centrum De Auw Sjoe?l Ubachsberg'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Stichting Museum Stedhés Sleat/Museum Sloten' WHERE ontvanger = 'Stichting Museum Stedh?s Sleat/Museum Sloten'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Negusé Nëgëst' WHERE ontvanger = 'Stichting Negus? N?g?st'; -- 2 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Stichting Oók FC Volendam' WHERE ontvanger = 'Stichting O?k FC Volendam'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Stichting Platform Bèta en Techniek' WHERE ontvanger = 'Stichting Platform B?ta en Techniek'; -- 9 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Société Musée Lalique Pays Bas' WHERE ontvanger = 'Stichting Soci?t? Mus?e Lalique Pays Bas'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Stichting Sociëteit Antigoon' WHERE ontvanger = 'Stichting Soci?teit Antigoon'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Sociëteit Clubhuis Paterswoldsemeer' WHERE ontvanger = 'Stichting Soci?teit Clubhuis Paterswoldsemeer'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Sociëteit De Walrus' WHERE ontvanger = 'Stichting Soci?teit De Walrus'; -- 2 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Sociëteit Flux' WHERE ontvanger = 'Stichting Soci?teit Flux'; -- 2 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Sociëteit Lanx ''91' WHERE ontvanger = 'Stichting Soci?teit Lanx ''91'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Sociëteit Reiderland' WHERE ontvanger = 'Stichting Soci?teit Reiderland'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Sociëteit UMTC' WHERE ontvanger = 'Stichting Soci?teit UMTC'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Sociëteit Volonte' WHERE ontvanger = 'Stichting Soci?teit Volonte'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Sociëteit het Amstelhuis' WHERE ontvanger = 'Stichting Soci?teit het Amstelhuis'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Sociëteitsbeheer' WHERE ontvanger = 'Stichting Soci?teitsbeheer'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Sociale Partners samen vóór duurzame inzetbaarheid' WHERE ontvanger = 'Stichting Sociale Partners samen v??r duurzame inzetbaarheid'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Stichting Stöppelhaene Raalte' WHERE ontvanger = 'Stichting St?ppelhaene Raalte'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Stichting Stadsbal La Résidance Den Haag' WHERE ontvanger = 'Stichting Stadsbal La R?sidance Den Haag'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Strijkkwartet Biénnale Amsterdam' WHERE ontvanger = 'Stichting Strijkkwartet Bi?nnale Amsterdam'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Tjongerhés' WHERE ontvanger = 'Stichting Tjongerh?s'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Us Doarpshés' WHERE ontvanger = 'Stichting Us Doarpsh?s'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Verhalenhuis Belvédére' WHERE ontvanger = 'Stichting Verhalenhuis Belv?d?re'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting Weekendschool Baljée' WHERE ontvanger = 'Stichting Weekendschool Balj?e'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Stichting de Bühne' WHERE ontvanger = 'Stichting de B?hne'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Stichting de Roerparel St. Odiliénberg' WHERE ontvanger = 'Stichting de Roerparel St. Odili?nberg'; -- 2 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting het Dordts Patriciérshuis' WHERE ontvanger = 'Stichting het Dordts Patrici?rshuis'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Stichting it Abbegeaster Skûtsje' WHERE ontvanger = 'Stichting it Abbegeaster Sk?tsje'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'TéBé B.V.' WHERE ontvanger = 'T?B? B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Tübben Gifts & Souvenirs B.V.' WHERE ontvanger = 'T?bben Gifts & Souvenirs B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Tûsken de Wâllen' WHERE ontvanger = 'T?sken de W?llen'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'TalmaWéld Ova B.V.' WHERE ontvanger = 'TalmaW?ld Ova B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Tennisferiening Feanwélden' WHERE ontvanger = 'Tennisferiening Feanw?lden'; -- 2 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Tentije Industriële Automatisering B.V.' WHERE ontvanger = 'Tentije Industri?le Automatisering B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Tenue de Nîmes EG B.V.' WHERE ontvanger = 'Tenue de N?mes EG B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Ter Laak Orchideeën B.V.' WHERE ontvanger = 'Ter Laak Orchidee?n B.V.'; -- 2 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Tovérli B.V.' WHERE ontvanger = 'Tov?rli B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Traiteur Délicat B.V.' WHERE ontvanger = 'Traiteur D?licat B.V.'; -- 2 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Tuincentrum Daniéls B.V.' WHERE ontvanger = 'Tuincentrum Dani?ls B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'VÉLO B.V.' WHERE ontvanger = 'V?LO B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Vörding Spirits B.V.' WHERE ontvanger = 'V?rding Spirits B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Véron B.V.' WHERE ontvanger = 'V?ron B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Van Geel Orchideeën B.V.' WHERE ontvanger = 'Van Geel Orchidee?n B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Vereniging Watersport De Twee Provincién' WHERE ontvanger = 'Vereniging Watersport De Twee Provinci?n'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Vervoer Coördinatie Centrum Rijnmond Advies B.V.' WHERE ontvanger = 'Vervoer Co?rdinatie Centrum Rijnmond Advies B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Villa Fiësta Eindhoven B.V.' WHERE ontvanger = 'Villa Fi?sta Eindhoven B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Voetbalkantine Stünfries' WHERE ontvanger = 'Voetbalkantine St?nfries'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Wadloopcentrum Fryslân' WHERE ontvanger = 'Wadloopcentrum Frysl?n'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Walsjérét B.V.' WHERE ontvanger = 'Walsj?r?t B.V.'; -- 2 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Willems Industriële Producties B.V.' WHERE ontvanger = 'Willems Industri?le Producties B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Wiro Wok Oriëntal B.V.' WHERE ontvanger = 'Wiro Wok Ori?ntal B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Yaël Kuijk Alkmaar B.V.' WHERE ontvanger = 'Ya?l Kuijk Alkmaar B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'Zeeën van Tijd B.V.' WHERE ontvanger = 'Zee?n van Tijd B.V.'; -- 1 row(s) [AUTO]
UPDATE instrumenten SET ontvanger = 'Zorgbelang Fryslân' WHERE ontvanger = 'Zorgbelang Frysl?n'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'hegé railinfra B.V.' WHERE ontvanger = 'heg? railinfra B.V.'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET ontvanger = 'il fiore healthcenters Maastricht (Céramique)' WHERE ontvanger = 'il fiore healthcenters Maastricht (C?ramique)'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET regeling = 'Beëindiging en saneringsregeling' WHERE regeling = 'Be?indiging en saneringsregeling'; -- 1 row(s) [MANUAL]
UPDATE instrumenten SET regeling = 'Coördinatie crisisdienstverlening' WHERE regeling = 'Co?rdinatie crisisdienstverlening'; -- 7 row(s) [AUTO]
UPDATE instrumenten SET regeling = 'Financiële sector ontwikkeling' WHERE regeling = 'Financi?le sector ontwikkeling'; -- 91 row(s) [AUTO]
UPDATE instrumenten SET regeling = 'Innovatieve onderzoeksprogrammaés' WHERE regeling = 'Innovatieve onderzoeksprogramma?s'; -- 15 row(s) [AUTO]
UPDATE instrumenten SET regeling = 'Subsidieregeling Jonge Agrariërs' WHERE regeling = 'Subsidieregeling Jonge Agrari?rs'; -- 3 row(s) [AUTO]

-- === provincie ===
UPDATE provincie SET omschrijving = '5 Regionale Economie - 6.2 Mit-Haalbaarheidsprojecten - Verbetering Proces En Materiaal EfficiéNtie Door A Priori Voetdrukmeting
UPDATE provincie SET omschrijving = 'Economie - Nappyés.nl groeiversnelling
UPDATE provincie SET ontvanger = 'En Moviéo Vastgoed B.V.' WHERE ontvanger = 'En Movi?o Vastgoed B.V.'; -- 2 row(s) [MANUAL]

-- ============================================================================
-- Verification: should return 0 rows if all question marks are fixed
-- ============================================================================

SELECT 'instrumenten.ontvanger' as location, COUNT(*) as remaining
FROM instrumenten 
WHERE (ontvanger ~ '[A-Za-z]\?[A-Za-z]' OR ontvanger ~ '^\?[a-z]') 
  AND ontvanger NOT LIKE '%#NAAM?%'
UNION ALL
SELECT 'instrumenten.regeling', COUNT(*)
FROM instrumenten 
WHERE regeling ~ '[A-Za-z]\?[A-Za-z]'
UNION ALL
SELECT 'inkoop.leverancier', COUNT(*)
FROM inkoop 
WHERE (leverancier ~ '[A-Za-z]\?[A-Za-z]' OR leverancier ~ '^\?[a-z]')
  AND leverancier NOT LIKE '%#NAAM?%';

COMMIT;
